---
output:
html_document:
theme: spacelab
---

Faculty Office Hour
=============

### Instructors: 

* [John Muschelli](http://johnmuschelli.com)

* [Sean Kross](http://seankross.com/)

### Online Videos of Lectures

```{r videos, echo = FALSE, message = FALSE, results='asis'}
library(pander)
library(kableExtra)
mat = matrix(c(
  "Git and GitHub", "https://www.youtube.com/watch?v=utJ-smwHe0M",
  "R Packages", "",
  "ggplot2 and dplyr", "https://youtu.be/B9xpjZ7MVUU"
), ncol = 2, byrow = TRUE)
mat = data.frame(mat, stringsAsFactors = FALSE)
colnames(mat) = c("Day", "Link to Video")
knitr::kable(mat, format = "html") %>% 
  kable_styling() 
rownames(mat) = mat$Day
```

## Lessons

[Tables](tables/index.html) and [Rmd](tables/index.Rmd).

### ggplot2 

[Common Plots in `ggplot2`](ggplot2/common_plots.R), used in [this video](`r mat["ggplot2 and dplyr", "Link to Video"]`)

### dplyr  

[Commonly used verbs in `dplyr`](dplyr/dplyr_verbs.R), used in [this video](`r mat["ggplot2 and dplyr", "Link to Video"]`)

## Find an Error!?

Feel free to submit typos/errors/etc via the github repository: 
https://github.com/muschellij2/Faculty_Office_Hour

```{r, eval = FALSE, echo = FALSE}
## Render this file:
rmarkdown::render('index.Rmd')
```

This page was last updated on `r Sys.time()` Eastern Time.
